[package]
name = "pastebin"
version = "0.0.0"
workspace = "../../"
edition = "2018"
publish = false

[dependencies]
rocket = { path = "../../core/lib" }
rand = "0.7"
[dependencies.rocket_contrib]
version = "0.4.6"
default-features = false
features = ["json"]